In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from sqlalchemy import create_engine
import pyodbc

In [9]:
pyodbc.drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [10]:
engine = create_engine(

 "mssql+pyodbc://DESKTOP-AMLNKU8/Olist_Brazilian?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&TrustServerCertificate=yes"
)

In [11]:
Customer= pd.read_sql('Select * From olist_customers_dataset',engine)
geolocation =pd.read_sql('Select * From olist_geolocation_dataset',engine)
order_items = pd.read_sql('Select * From olist_order_items_dataset',engine)
order_payments = pd.read_sql('Select * From olist_order_payments_dataset',engine)
order_reviews = pd.read_sql('Select * From olist_order_reviews_dataset',engine)
Orders = pd.read_sql('Select * From olist_orders_dataset',engine)
Products = pd.read_sql ('Select * From olist_products_dataset',engine)
sellers = pd.read_sql ('Select * From olist_sellers_dataset',engine)
product_category_name = pd.read_sql('Select * From product_category_name_translation',engine)

In [12]:
Customer.shape

(99441, 5)

In [13]:
Products.shape

(32951, 9)

In [14]:
geolocation.shape

(1000163, 5)

In [15]:
order_items.shape

(112650, 7)

In [16]:
order_payments.shape

(103886, 5)

In [17]:
order_reviews.shape

(99224, 7)

In [18]:
Orders.shape

(99441, 8)

In [19]:
sellers.shape

(3095, 4)

In [20]:
product_category_name.shape

(72, 2)

In [21]:
Products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [22]:
product_category_name.columns

Index(['product_category_name', 'product_category_name_english'], dtype='str')

In [26]:
product_category_name.shape

(71, 2)

In [27]:
dataframes = {
    'Customer': Customer,
    'geolocation': geolocation,
    'order_items': order_items,
    'order_payments': order_payments,
    'order_reviews': order_reviews,
    'Orders': Orders,
    'Products': Products,
    'sellers': sellers,
    'product_category_name': product_category_name
}

# Python Cleaning Checklist

In [28]:
for i,e in dataframes.items():
    print(f'\n   {i}   ')
# 1. Null Values
    print(f'\n Null:')
    print(e.isnull().sum())
# 2. Duplicate Rows
    print(f'\n Dublicate:')
    print(e.duplicated().sum())
# 3. Data Types
    print(f'\n Types')
    print(e.dtypes)

   Customer

 Null:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

 Dublicate:
0

 Types
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

   geolocation

 Null:
geolocation_zip_code_prefix       0
geolocation_lat                1336
geolocation_lng                   3
geolocation_city                  0
geolocation_state                 0
dtype: int64

 Dublicate:
262154

 Types
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

   order_items

 Null:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

 Dublicate:
0

 Types
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

   order_payments

 Null:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 Dublicate:
0

 Types
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

   order_reviews

 Null:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87658
review_comment_message     58256
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 Dublicate:
0

 Types
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

   Orders

 Null:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

 Dublicate:
0

 Types
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

   Products

 Null:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

 Dublicate:
0

 Types
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

   sellers

 Null:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 Dublicate:
0

 Types
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

   product_category_name

 Null:
product_category_name            0
product_category_name_english    0
dtype: int64

 Dublicate:
0

 Types
product_category_name            str
product_category_name_english    str
dtype: object

In [ ]:
for i,e in dataframes.items():
    Nulls = e.isnull().sum()
    if Nulls.sum() > 0 :
        print(f'\n  {i}  ')
        print(Nulls[Nulls > 0])

  geolocation
geolocation_lat    1336
geolocation_lng       3
dtype: int64

  order_reviews
review_comment_title      87658
review_comment_message    58256
dtype: int64

  Orders
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

  Products
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [30]:
Products[Products['product_category_name'].isnull()].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [31]:
Products[Products['product_category_name'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
52,0082684bb4a60a862baaf7a60a5845ed,NaN,NaN,NaN,NaN,500.0,24.0,4.0,15.0
72,00ab8a8b9fe219511dc3f178c6d79698,NaN,NaN,NaN,NaN,2100.0,50.0,30.0,30.0
93,00d62b338366db4c4aec8547ea8f928e,NaN,NaN,NaN,NaN,400.0,24.0,4.0,15.0
119,0103863bf3441460142ec23c74388e4c,NaN,NaN,NaN,NaN,200.0,16.0,2.0,11.0
164,014fcf6bd5cd4c7ee29fb3bb618c445e,NaN,NaN,NaN,NaN,7000.0,55.0,30.0,45.0
...,...,...,...,...,...,...,...,...,...
32784,fedccbd5e370e8ddb7aae6fb4cb70347,NaN,NaN,NaN,NaN,1200.0,20.0,20.0,20.0
32804,ff09b38ea3889c433325e313807936ea,NaN,NaN,NaN,NaN,1600.0,16.0,36.0,13.0
32853,ff6caf9340512b8bf6d2a2a6df032cfa,NaN,NaN,NaN,NaN,200.0,16.0,5.0,12.0
32870,ff8bb42702f38636b348fd7e2332ce2f,NaN,NaN,NaN,NaN,100.0,25.0,2.0,17.0
32944,fff28f91211774864a1000f918ed00cc,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0

In [32]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [33]:
missing_category_products = Products[Products['product_category_name'].isnull()]

In [34]:
missing_category_products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
52,0082684bb4a60a862baaf7a60a5845ed,NaN,NaN,NaN,NaN,500.0,24.0,4.0,15.0
72,00ab8a8b9fe219511dc3f178c6d79698,NaN,NaN,NaN,NaN,2100.0,50.0,30.0,30.0
93,00d62b338366db4c4aec8547ea8f928e,NaN,NaN,NaN,NaN,400.0,24.0,4.0,15.0
119,0103863bf3441460142ec23c74388e4c,NaN,NaN,NaN,NaN,200.0,16.0,2.0,11.0
164,014fcf6bd5cd4c7ee29fb3bb618c445e,NaN,NaN,NaN,NaN,7000.0,55.0,30.0,45.0
...,...,...,...,...,...,...,...,...,...
32784,fedccbd5e370e8ddb7aae6fb4cb70347,NaN,NaN,NaN,NaN,1200.0,20.0,20.0,20.0
32804,ff09b38ea3889c433325e313807936ea,NaN,NaN,NaN,NaN,1600.0,16.0,36.0,13.0
32853,ff6caf9340512b8bf6d2a2a6df032cfa,NaN,NaN,NaN,NaN,200.0,16.0,5.0,12.0
32870,ff8bb42702f38636b348fd7e2332ce2f,NaN,NaN,NaN,NaN,100.0,25.0,2.0,17.0
32944,fff28f91211774864a1000f918ed00cc,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0

In [40]:
order_items['product_id'].isin(missing_category_products).sum()

np.int64(0)

In [47]:
for i,e in dataframes.items():
    Nulls = e.isnull().sum()
    if Nulls.sum() > 0 :
        print(f'\n  {i}  ')
        print(Nulls[Nulls > 0])

  geolocation
geolocation_lat    1336
geolocation_lng       3
dtype: int64

  order_reviews
review_comment_title      87658
review_comment_message    58256
dtype: int64

  Orders
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

  Products
product_category_name         609
product_name_lenght           609
product_description_lenght    609
product_photos_qty            609
dtype: int64

In [43]:
Products[Products['product_weight_g'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1275,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
12265,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
Products.dropna(subset=['product_weight_g'], inplace=True)
Products.dropna(subset=['product_height_cm'], inplace=True)
Products.dropna(subset=['product_width_cm'], inplace=True)

In [59]:
Orders[Orders['order_approved_at'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
251,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12
309,00d0ffd14774da775ac832ba8520510f,a2f3de2a0a84803cef018776a2e76c9b,canceled,2017-12-23 22:25:00,NaT,NaT,NaT,2018-01-19
1114,02e723e8edb4a123d414f56cc9c4665e,6e9f7d9e943f9c0bdea278d9d7a1c9b9,canceled,2017-08-18 14:30:19,NaT,NaT,NaT,2017-09-21
1215,032cf17f7a713287e46999fddea6051b,7ec44117b7760d297447f1cff2a10967,canceled,2016-10-07 12:21:07,NaT,NaT,NaT,2016-11-17
1224,03310aa823a66056268a3bab36e827fb,25dbbf0c477fd4ae0880aaffbb12e8b3,canceled,2018-08-07 16:33:59,NaT,NaT,NaT,2018-09-04
...,...,...,...,...,...,...,...,...
92195,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaT,NaT,NaT,2018-10-17
95040,f4a8cf5dcabdbe8dd7e65e1674db3015,f46fbb1f9d19890a021e112d9e67c4c0,canceled,2018-01-21 23:26:18,NaT,NaT,NaT,2018-02-06
96360,f81e71dd7c044a9ee7c1d6e37d68d64f,953f71324f3a770118c88a42363655b2,canceled,2018-08-15 08:34:42,NaT,NaT,NaT,2018-09-12
96493,f86d7bc39aab05299691322044b63bb2,ff31bee1ba4bba00cc14b1b91c8d28f3,canceled,2018-08-13 18:43:06,NaT,NaT,NaT,2018-09-25
98412,fd4c3a2912e854eedd463b329540da4b,d2fdd1d3725bccaa0900e360a985398f,canceled,2017-10-28 11:18:48,NaT,NaT,NaT,2017-11-21

In [53]:
Orders[Orders['order_delivered_carrier_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
24,0010dedd556712d7bb69a19cb7bbd37a,3a92efdb6e6163dc1734d44f2f5f6d04,unavailable,2017-10-21 19:32:06,2017-10-24 03:25:32,NaT,NaT,2017-11-03
77,00310b0c75bb13015ec4d82d341865a4,0dad07848c618cc5a4679a1bfe1db8d2,canceled,2018-08-15 14:29:08,2018-08-15 15:04:25,NaT,NaT,2018-08-29
229,00a500bc03bc4ec968e574c2553bed4b,3d2f26eab3f79dd1fe9977f615e70c2f,unavailable,2017-11-23 10:53:01,2017-11-25 10:54:38,NaT,NaT,2018-01-08
246,00ae7a8b4936674ebb701d4a23719a79,a7e8a3cb55d9c9a536992c6465a46a3f,canceled,2018-05-09 14:14:06,2018-05-09 15:51:32,NaT,NaT,2018-05-17
251,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12
...,...,...,...,...,...,...,...,...
98957,feae5ecdf2cc16c1007741be785fe3cd,ca05f8b53b1ad2a64bf34baa8aa7f4f6,unavailable,2017-11-11 16:41:06,2017-11-11 16:56:15,NaT,NaT,2017-11-27
98990,fec76d3c7d37a989bdd3a22911340c75,ca8fb6422920b579e8d074784240c05f,processing,2018-01-19 14:24:31,2018-01-20 15:22:02,NaT,NaT,2018-02-09
98995,fecc4ea5a3e06ce3192ae2f05b7a8439,ec43686dd7b2f48ea65475606fdfc85d,processing,2018-01-14 21:52:31,2018-01-14 22:09:08,NaT,NaT,2018-02-06
99238,ff7140ba310a4717112d39c0cd0b4062,3c97bdeb3712ffcfa72a09bf0a8a3e95,processing,2017-05-19 18:11:21,2017-05-19 18:30:27,NaT,NaT,2017-06-26
99239,ff71fa43cf5b726cd4a5763c7d819a35,14217d5d9e2e67faaae493aa0a181d4c,unavailable,2017-07-19 21:53:57,2017-07-21 02:50:44,NaT,NaT,2017-08-10

In [54]:
Orders[Orders['order_delivered_customer_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
24,0010dedd556712d7bb69a19cb7bbd37a,3a92efdb6e6163dc1734d44f2f5f6d04,unavailable,2017-10-21 19:32:06,2017-10-24 03:25:32,NaT,NaT,2017-11-03
73,002f19a65a2ddd70a090297872e6d64e,7fa80efb1ef15ca4104627910c29791c,shipped,2018-03-21 13:05:30,2018-03-21 13:15:27,2018-03-22 00:13:35,NaT,2018-04-16
77,00310b0c75bb13015ec4d82d341865a4,0dad07848c618cc5a4679a1bfe1db8d2,canceled,2018-08-15 14:29:08,2018-08-15 15:04:25,NaT,NaT,2018-08-29
229,00a500bc03bc4ec968e574c2553bed4b,3d2f26eab3f79dd1fe9977f615e70c2f,unavailable,2017-11-23 10:53:01,2017-11-25 10:54:38,NaT,NaT,2018-01-08
236,00a99c50fdff7e36262caba33821875a,7a399396442d5601cbedfbd0a3cf1da4,shipped,2018-08-17 16:25:04,2018-08-17 16:35:18,2018-08-18 09:07:00,NaT,2018-09-18
...,...,...,...,...,...,...,...,...
99089,ff0768e3356919b32e3d7f30baecfcfb,f3e5d57c12abb230c4f16b6a0a23d7f7,shipped,2018-04-04 22:58:39,2018-04-04 23:10:13,2018-04-05 22:59:25,NaT,2018-04-23
99162,ff358345576214cc9e08488188973c84,8da33bbf65a0b181486063ffb90fa3d6,shipped,2018-03-03 17:05:12,2018-03-03 17:29:04,2018-03-05 17:18:58,NaT,2018-04-02
99203,ff536d93ae4214b4d51c2894ccfc569f,8891eb5ca0e28df961b2b5b8f3c0eb23,shipped,2017-12-21 09:01:00,2017-12-22 12:33:26,2018-01-03 18:22:09,NaT,2018-01-10
99238,ff7140ba310a4717112d39c0cd0b4062,3c97bdeb3712ffcfa72a09bf0a8a3e95,processing,2017-05-19 18:11:21,2017-05-19 18:30:27,NaT,NaT,2017-06-26
99239,ff71fa43cf5b726cd4a5763c7d819a35,14217d5d9e2e67faaae493aa0a181d4c,unavailable,2017-07-19 21:53:57,2017-07-21 02:50:44,NaT,NaT,2017-08-10

In [56]:
order_reviews[order_reviews['review_comment_title'].isnull()]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

# Data Transformation

In [61]:
for i, e in dataframes.items():
    print(f"\n--- {i} ---")
    print(e.dtypes)

--- Customer ---
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

--- geolocation ---
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

--- order_items ---
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

--- order_payments ---
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

--- order_reviews ---
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

--- Orders ---
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

--- Products ---
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

--- sellers ---
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

--- product_category_name ---
product_category_name            str
product_category_name_english    str
dtype: object

In [62]:
for i, e in dataframes.items():
    date_cols = e.select_dtypes(include=['datetime']).columns
    if len(date_cols) > 0:
        print(f'\n   {i} ')
        print(list[date_cols])

   order_items
list[Index(['shipping_limit_date'], dtype='str')]

   order_reviews
list[Index(['review_creation_date', 'review_answer_timestamp'], dtype='str')]

   Orders
list[Index(['order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date'],
      dtype='str')]

# Data Validation

In [66]:
Orders['delivery_days']=(Orders['order_delivered_customer_date']-Orders['order_purchase_timestamp']).dt.days

In [69]:
Orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_days', 'delivery_delay_days'],
      dtype='str')

In [68]:
Orders['delivery_delay_days']= (Orders['order_delivered_customer_date']-Orders['order_estimated_delivery_date']).dt.days

In [72]:
order_items['Total price '] = (order_items['price']+order_items['freight_value'])

In [73]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'Total price '],
      dtype='str')

In [74]:
order_items.head(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Total price
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000,72.190001
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000,259.829994
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001,216.870001

# Data Validation

In [75]:
for i,e in dataframes.items():
    Nulls = e.isnull().sum()
    if Nulls.sum() > 0 :
        print(f'\n  {i}  ')
        print(Nulls[Nulls > 0])

  geolocation
geolocation_lat    1336
geolocation_lng       3
dtype: int64

  order_reviews
review_comment_title      87658
review_comment_message    58256
dtype: int64

  Orders
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
delivery_days                    2965
delivery_delay_days              2965
dtype: int64

  Products
product_category_name         609
product_name_lenght           609
product_description_lenght    609
product_photos_qty            609
dtype: int64

In [76]:
for i,e in dataframes.items():
    print(f"{i}: {e.duplicated().sum()} duplicate rows")

Customer: 0 duplicate rows
geolocation: 262154 duplicate rows
order_items: 0 duplicate rows
order_payments: 0 duplicate rows
order_reviews: 0 duplicate rows
Orders: 0 duplicate rows
Products: 0 duplicate rows
sellers: 0 duplicate rows
product_category_name: 0 duplicate rows

In [77]:
for i, e in dataframes.items():
    print(f"\n--- {i} ---")
    print(e.dtypes)

--- Customer ---
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

--- geolocation ---
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

--- order_items ---
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
Total price                   float64
dtype: object

--- order_payments ---
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

--- order_reviews ---
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

--- Orders ---
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivery_days                           float64
delivery_delay_days                     float64
dtype: object

--- Products ---
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

--- sellers ---
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

--- product_category_name ---
product_category_name            str
product_category_name_english    str
dtype: object

In [ ]:
import os

output_folder = "Olist_Cleaned_Data"
os.makedirs(output_folder, exist_ok=True)

for name, df in dataframes.items():
    df.to_csv(f"{output_folder}/{name}.csv", index=False, encoding="utf-8-sig")